---
name: lutrachat

packages:
  - packages/*
  - packages/*/*

scripts:
  build_runner:build:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
      orderDependents: true
    packageFilters:
      dependsOn:
        - build_runner

  build_runner:watch:
    run: dart run build_runner watch --delete-conflicting-outputs
    exec:
      failFast: true
      orderDependents: true
    packageFilters:
      dependsOn:
        - build_runner

  buf:generate:
    run: cd proto && buf generate
    exec:
      failFast: true
      orderDependents: true
    packageFilters:
      dirExists:
        - proto
      fileExists:
        - proto/buf.yaml
        - proto/buf.gen.yaml
      dependsOn:
        - protobuf

  pub:outdated:
    exec: dart pub outdated

  slang:
    run: dart run slang
    exec:
      failFast: true
      orderDependents: true
    packageFilters:
      dependsOn:
        - slang

ide:
  intellij:
    moduleNamePrefix: ''
