---
name: lutrachat_protocol
version: 1.0.0
description: Protocol code for LutraChat components.

repository: https://github.com/lutracorp/lutrachat
issue_tracker: https://github.com/lutracorp/lutrachat/issues

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  lutrachat_common: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
