---
name: lutrachat_protocol
version: 1.0.0
description: Protocol code for LutraChat components.

repository: https://github.com/lutracorp/lutrachat
issue_tracker: https://github.com/lutracorp/lutrachat/issues

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  foxid: ^1.2.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  lutrachat_common: ^1.0.0
  protobuf: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.8

dependency_overrides:
  injectable:
    git:
      url: https://github.com/kasefuchs/injectable
      path: injectable

  injectable_generator:
    git:
      url: https://github.com/kasefuchs/injectable
      path: injectable_generator
