---
include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    implicit_call_tearoffs: ignore
    empty_catches: ignore

linter:
  rules:
    - prefer_relative_imports
