---
name: lutrachat_mobile_app
version: 1.0.0
description: LutraChat mobile application.

repository: https://github.com/lutracorp/lutrachat
issue_tracker: https://github.com/lutracorp/lutrachat/issues

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dart_random_choice: ^0.2.0
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.4
  lutrachat_mobile_i18n: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
