---
name: lutrachat_backend_rest
version: 1.0.0
description: REST API for communication with LutraChat.

repository: https://github.com/lutracorp/lutrachat
issue_tracker: https://github.com/lutracorp/lutrachat/issues

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dartfield: ^1.2.1
  foxid: ^1.2.2
  freezed_annotation: ^2.4.3
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  luthor: ^0.4.2+1
  lutrachat_backend_common: ^1.0.0
  lutrachat_backend_database: ^1.0.0
  lutrachat_backend_protocol: ^1.0.0
  lutrachat_backend_server: ^1.0.0
  shelf: ^1.4.2
  shelf_plus: ^1.9.2

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.6
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  lints: ^4.0.0
  luthor_generator: ^0.4.5
  test: ^1.25.8

dependency_overrides:
  injectable:
    git:
      url: https://github.com/kasefuchs/injectable
      path: injectable

  injectable_generator:
    git:
      url: https://github.com/kasefuchs/injectable
      path: injectable_generator
