---
name: lutrachat_gateway
version: 1.0.0
description: A gateway for real-time communication with LutraChat.

repository: https://github.com/lutracorp/lutrachat
issue_tracker: https://github.com/lutracorp/lutrachat/issues

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  lutrachat_common: ^1.0.0
  lutrachat_database: ^1.0.0
  lutrachat_protocol: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
