---
name: lutrachat_backend_database
version: 1.0.0
description: Database code for LutraChat components.

repository: https://github.com/lutracorp/lutrachat
issue_tracker: https://github.com/lutracorp/lutrachat/issues

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dartfield: ^1.2.1
  drift: ^2.19.1
  drift_postgres: ^1.3.0
  foxid: ^1.2.2
  freezed_annotation: ^2.4.3
  get_it: ^7.7.0
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  lutrachat_backend_common: ^1.0.0
  postgres: ^3.2.1

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.19.0
  freezed: ^2.5.6
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.8
